name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Conda and create environment
      run: |
        conda install -y conda
        conda create -n myenv python=3.8 numpy pandas -y
      shell: bash

    - name: Activate Conda environment and install packages
      run: |
        source activate myenv
        conda install -y flake8 pytest
      shell: bash

    - name: Lint with flake8
      run: |
        source activate myenv
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash

    - name: Test with pytest
      run: |
        source activate myenv
        pytest
      shell: bash

